// SharedViewer: decodes a play from a base64 URL segment and renders it read-only.
// The decoded play is NOT persisted to localStorage automatically : viewers can
// click "Save to my library" to opt-in. That keeps shared links from silently
// polluting a coach's library.

import { Link, useParams, useNavigate } from 'react-router-dom';
import { useMemo, useState } from 'react';
import { Library, Save, AlertTriangle, Check } from 'lucide-react';
import PlayStage from './PlayStage.jsx';
import { decodePlayFromUrl, savePlay } from '../data/storage.js';
import { validatePlay } from '../data/schema.js';

export default function SharedViewer() {
  const { encoded } = useParams();
  const navigate = useNavigate();

  const { play, error } = useMemo(() => {
    try {
      const decoded = decodePlayFromUrl(encoded ?? '');
      const { ok, errors } = validatePlay(decoded);
      if (!ok) return { play: null, error: 'Invalid play: ' + errors.join('; ') };
      return { play: decoded, error: null };
    } catch (e) {
      return { play: null, error: e?.message ?? 'Could not decode link' };
    }
  }, [encoded]);

  const [savedMsg, setSavedMsg] = useState(null);

  const handleSaveToLibrary = () => {
    if (!play) return;
    try {
      // Give it a fresh id so it doesn't collide with a locally-saved copy.
      const copy = { ...play, meta: { ...play.meta, id: crypto.randomUUID(), updatedAt: Date.now() } };
      const saved = savePlay(copy);
      setSavedMsg('Saved');
      setTimeout(() => navigate(`/play/${saved.meta.id}`), 600);
    } catch (e) {
      setSavedMsg('Save failed: ' + (e?.message ?? 'unknown error'));
    }
  };

  if (error) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="panel p-6">
          <p className="text-sm text-red-300 flex items-center gap-2">
            <AlertTriangle size={16} /> {error}
          </p>
          <p className="text-sm text-slate-400 mt-2">
            This share link is malformed or was generated by an incompatible version.
          </p>
          <Link to="/" className="btn-secondary mt-4 inline-flex">
            <Library size={14} /> Back to library
          </Link>
        </div>
      </div>
    );
  }

  const header = (
    <div className="flex items-center justify-between mb-3 gap-2 flex-wrap">
      <div>
        <p className="text-xs text-slate-400">Shared · {play?.meta.type}</p>
        <h1 className="text-lg font-semibold text-slate-100">{play?.meta.name}</h1>
      </div>
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={handleSaveToLibrary}
          className="btn-ghost text-sm"
          title="Save a copy to your library"
        >
          {savedMsg === 'Saved' ? <><Check size={14} /> Saved</> : <><Save size={14} /> Save to library</>}
        </button>
        <Link to="/" className="btn-secondary text-sm">
          <Library size={14} /> Library
        </Link>
      </div>
    </div>
  );

  return <PlayStage play={play} header={header} />;
}
